import {
  LayoutGrid,
  Megaphone,
  BarChart2,
  CreditCard,
  Heart,
  Users2,
  Smartphone,
  Shield,
  Zap,
  Target,
  Flame,
  Activity,
  TrendingUp,
  UserCheck,
  Briefcase,
  Wifi,
  Lock,
  Clock
} from "lucide-react";

import exercise from "../../../../assets/crm/exercise-library.png";
import nutrition from "../../../../assets/crm/nutrition.png";
import dashboard from "../../../../assets/crm/dashboard.webp";
import payments from "../../../../assets/crm/payments.png";
import chat from "../../../../assets/crm/chat.png";
import team from "../../../../assets/crm/team.png";

import programavatar from "../../../../assets/crm/avatar/avatar1.png";
import nutritionavatar from "../../../../assets/crm/avatar/avatar6.png";
import dashboardavatar from "../../../../assets/crm/avatar/avatar5.png";




export const FEATURES = [
  {
    id: 0,
    key: "Program Management",
    label: "Program Management",
    Icon: LayoutGrid,
    agentName: "Coach",
    agentImage: programavatar,
    agentStat: "New Program Created",
    AgentStatIcon: Target,
    agentColor: "from-violet-400 to-indigo-500",
    agentEmoji: programavatar,
    screenshotImage: exercise,
    screenshotImageMobile: exercise,
    floatingLabels: ["Auto-schedule tasks", "Sprint velocity +32%"],
  },
  {
    id: 1,
    key: "Nutrition & Activity",
    label: "Nutrition & Activity",
    Icon: Megaphone,
     agentName: "Dietician",
    agentImage: nutritionavatar,
    agentStat: "1,240 meal plans generated",
    AgentStatIcon: Flame,
    agentColor: "from-purple-400 to-violet-400",
    agentEmoji: "🥗",
    screenshotImage: nutrition,
    screenshotImageMobile: nutrition,
    floatingLabels: ["Daily macro tracker", "86% goal completion"],
  },
  {
    id: 2,
    key: "Dashboards & Reports",
    label: "Dashboards & Reports",
    Icon: BarChart2,
    agentName: "Sales Agent",
    agentImage: dashboardavatar,
    agentStat: "50 new leads this week",
    AgentStatIcon: Activity,
    agentColor: "from-blue-400 to-cyan-400",
    agentEmoji: "📊",
    screenshotImage: dashboard,
    screenshotImageMobile: dashboard,
    floatingLabels: ["Real-time analytics", "Export to PDF/CSV"],
  },
  {
    id: 3,
    key: "payment",
    label: "Payments & Revenue",
    Icon: CreditCard,
    agentName: "Revenue Bot AI",
    agentStat: "₹4.2M processed this month",
    AgentStatIcon: TrendingUp,
    agentColor: "from-emerald-400 to-teal-500",
    agentEmoji: "💳",
    screenshotImage: payments,
    screenshotImageMobile: payments,
    floatingLabels: ["Auto-reconcile invoices", "0.1% failure rate"],
  },
  {
    id: 4,
    key: "Client Engagement",
    label: "Client Engagement",
    Icon: Heart,
    agentName: "Client Flow AI",
    agentStat: "2,340 active clients managed",
    AgentStatIcon: UserCheck,
    agentColor: "from-pink-400 to-rose-500",
    agentEmoji: "🤝",
    screenshotImage: chat,
    screenshotImageMobile: chat,
    floatingLabels: ["Smart follow-up nudges", "NPS score: 94"],
  },
  {
    id: 5,
    key: "team_management",
    label: "Team & Organisation Management",
    Icon: Users2,
    agentName: "OrgChart AI",
    agentStat: "38 team members synced",
    AgentStatIcon: Briefcase,
    agentColor: "from-amber-400 to-yellow-400",
    agentEmoji: "🏢",
    screenshotImage: team,
    screenshotImageMobile: team,
    floatingLabels: ["Role-based permissions", "1-click org restructure"],
  },
  {
    id: 6,
    key: "app",
    label: "Mobile App iOS & Android",
    Icon: Smartphone,
    agentName: "AppSync AI",
    agentStat: "99.98% uptime across devices",
    AgentStatIcon: Wifi,
    agentColor: "from-indigo-400 to-purple-500",
    agentEmoji: "📱",
    screenshotImage: "/screenshots/hero-app.avif",
    screenshotImageMobile: "/screenshots/hero-app-mobile.avif",
    floatingLabels: ["Push notifications live", "Offline mode enabled"],
  },
  {
    id: 7,
    key: "security",
    label: "Security & Compliance",
    Icon: Shield,
    agentName: "SecureWatch AI",
    agentStat: "0 breaches · 100% audit ready",
    AgentStatIcon: Lock,
    agentColor: "from-red-400 to-rose-500",
    agentEmoji: "🔐",
    screenshotImage: "/screenshots/hero-security.avif",
    screenshotImageMobile: "/screenshots/hero-security-mobile.avif",
    floatingLabels: ["GDPR · HIPAA compliant", "Threat scan: all clear"],
  },
  {
    id: 8,
    key: "workflows",
    label: "Business Automation",
    Icon: Zap,
    agentName: "FlowForge AI",
    agentStat: "127 automations saved 340 hrs",
    AgentStatIcon: Clock,
    agentColor: "from-cyan-400 to-blue-500",
    agentEmoji: "⚡",
    screenshotImage: "/screenshots/hero-workflows.avif",
    screenshotImageMobile: "/screenshots/hero-workflows-mobile.avif",
    floatingLabels: ["Zero-code automation", "Trigger → Action → Done"],
  },
];